version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${db_user}
      POSTGRES_PASSWORD: ${db_pass}
      POSTGRES_DB: ${db_name}
    ports:
      - "5432:5432"


  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url_shortener
    ports:
      - "8000:8000"
    networks:
      - backend_network
    depends_on:
      - db
    restart: always

networks:
  backend_network:
    driver: bridge

volumes:
  pg:
