version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${db_user}
      POSTGRES_PASSWORD: ${db_pass}
      POSTGRES_DB: ${db_name}
    ports:
      - "5432:5432"
    networks:
      - backend
    restart: always


  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url_shortener
    environment:
      PORT: ${PORT}
      db_user: ${db_user}
      db_name: ${db_name}
      db_pass: ${db_pass}
      db_host: postgres
    ports:
      - ${PORT}:${PORT}
    networks:
      - backend
    depends_on:
      - postgres
    restart: always

networks:
  backend:
    driver: bridge

volumes:
  pg:
